class Links:
    HOST = "https://parabank.parasoft.com/parabank"
    HOME_PAGE = f"{HOST}/index.htm"
    LOGIN_PAGE = f"{HOST}/login.htm"
    REGISTER_PAGE = f"{HOST}/register.htm"
    CUSTOMER_LOOKUP_PAGE = f"{HOST}/lookup.htm"
    OPEN_ACCOUNT_PAGE = f"{HOST}/openaccount.htm"
    ACCOUNTS_OVERVIEW_PAGE = f"{HOST}/overview.htm"
    TRANSFER_FUNDS_PAGE = f"{HOST}/transfer.htm"
    BILL_PAY_PAGE = f"{HOST}/billpay.htm"
    FIND_TRANSACTIONS_PAGE = f"{HOST}/findtrans.htm"
    UPDATE_CONTACT_INFO_PAGE = f"{HOST}/updateprofile.htm"
    REQUEST_LOAN_PAGE = f"{HOST}/requestloan.htm"
    LOGOUT_PAGE = f"{HOST}/index.htm?ConnType=JDBC"
    ABOUT_US_PAGE = f"{HOST}/about.htm"
    CUSTOMER_CARE_PAGE = f"{HOST}/contact.htm"
